version: 2
updates:
- package-ecosystem: npm
  directory: "/server"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.14.2
    - 4.15.1
    - 4.16.1
    - 4.19.0
    - 4.21.0
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.19.0
- package-ecosystem: npm
  directory: "/client"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: antd
    versions:
    - 4.14.1
    - 4.15.2
  - dependency-name: "@testing-library/user-event"
    versions:
    - 13.0.16
    - 13.1.0
  - dependency-name: "@types/node"
    versions:
    - 14.14.34
  - dependency-name: "@apollo/client"
    versions:
    - 3.3.10
  - dependency-name: "@ant-design/icons"
    versions:
    - 4.5.0
